name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: haskell/actions/setup@v2
      with:
        ghc-version: '8.8.4'
        cabal-version: '3.0.0.0'
      
    - name: Build
      run: make build

    - name: Doctest
      run: make doctest
      
    - name: Test
      run: make testing
